import { FormEvent, useEffect, useState } from 'react'
import { LoaderCircle, Plus, X } from 'lucide-react'
import { adminApi, ApiError } from '../services/api'
import ImageUploader from '../components/ImageUploader'
import type { ImageAsset, Project } from '../types'

const emptyProject = { name: '', slug: '', description: '', category: 'general', image: undefined as ImageAsset | undefined, isPublished: true, order: 0 }

export default function ProjectsPage() {
  const [projects, setProjects] = useState<Project[]>([])
  const [form, setForm] = useState(emptyProject)
  const [showForm, setShowForm] = useState(false)
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')
  const load = () => { setLoading(true); adminApi.getProjects().then(setProjects).catch((requestError) => setError(requestError instanceof ApiError ? requestError.message : 'Unable to load projects.')).finally(() => setLoading(false)) }
  useEffect(load, [])
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(''); try { const created = await adminApi.createProject(form); setProjects((current) => [...current, created]); setForm(emptyProject); setShowForm(false) } catch (saveError) { setError(saveError instanceof ApiError ? saveError.message : 'Unable to create project.') } finally { setSaving(false) } }
  return <div className="admin-page"><div className="admin-page-intro"><div><span className="admin-eyebrow">CONTENT / PROJECTS</span><h2>Project garage</h2><p>{projects.length} published project{projects.length === 1 ? '' : 's'} in the public catalogue.</p></div><button className="admin-button" onClick={() => setShowForm(true)}><Plus size={17} /> Add project</button></div>{error && <div className="admin-notice error">{error}</div>}{showForm && <form className="admin-panel admin-form-modal" onSubmit={submit}><button type="button" className="admin-icon-button" aria-label="Close form" onClick={() => setShowForm(false)}><X size={18} /></button><span className="admin-eyebrow">NEW PROJECT</span><h3>Put it on the grid</h3><div className="admin-field-grid"><label>Name<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label>Slug<input required pattern="[a-z0-9-]+" value={form.slug} onChange={(event) => setForm({ ...form, slug: event.target.value })} /></label><label>Category<input value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })} /></label><label>Order<input type="number" value={form.order} onChange={(event) => setForm({ ...form, order: Number(event.target.value) })} /></label></div><label>Description<textarea rows={4} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label><label>Published<select value={form.isPublished ? 'yes' : 'no'} onChange={(event) => setForm({ ...form, isPublished: event.target.value === 'yes' })}><option value="yes">Published</option><option value="no">Draft</option></select></label><ImageUploader page="projects" value={form.image} onChange={(image) => setForm({ ...form, image })} /><button className="admin-submit admin-submit-small" disabled={saving}>{saving ? <LoaderCircle className="admin-spin" size={17} /> : 'Create project'}</button></form>}<section className="admin-card-grid">{loading ? <div className="admin-loading"><LoaderCircle className="admin-spin" size={22} /> Loading projects...</div> : projects.length ? projects.map((project) => <article className="admin-content-card" key={project._id}><div className="admin-card-image">{project.image?.url && <img src={project.image.url} alt="" />}</div><div><span className="admin-card-kicker">{project.category}</span><h3>{project.name}</h3><p>{project.description || 'No description yet.'}</p><small>/{project.slug} · order {project.order}</small></div><span className="admin-status">{project.isPublished ? 'Published' : 'Draft'}</span></article>) : <div className="admin-empty">No projects found.</div>}</section><p className="admin-muted">Editing and deletion are unavailable because the current backend exposes project creation only.</p></div>
}
